{{- if .Values.coapgateway.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plgd-cloud.coapgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-cloud.coapgateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.coapgateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "plgd-cloud.coapgateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plgd-cloud.coapgateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext.coapgateway }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.coapgateway.restartPolicy }}
      containers:
        - name: {{ .Values.coapgateway.name }}
          image: {{ template "plgd-cloud.coapgateway.image" . }}
          ports:
            - name: coaps
              containerPort: {{ .Values.coapgateway.coapsPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "plgd-cloud.clientAuthCfg" . }}
          env:
            - name: LOG_ENABLE_DEBUG
              value: {{ .Values.coapgateway.debug | quote }}
            - name: EXTERNAL_PORT
              value: {{ .Values.coapgateway.coapsPort  | quote}}
            - name: FQDN
              value: {{ .Values.coapgateway.fqdn | quote }}
            - name: ADDRESS
              value: "0.0.0.0:{{ .Values.coapgateway.coapsPort }}"
            - name: DISABLE_BLOCKWISE_TRANSFER
              value: "true"
            - name: DISABLE_PEER_TCP_SIGNAL_MESSAGE_CSMS
              value: "true"
            - name: AUTH_SERVER_ADDRESS
              value: {{ include "plgd-cloud.authorizationserver.address" . | quote }}
            - name: RESOURCE_AGGREGATE_ADDRESS
              value: {{ include "plgd-cloud.resourceaggregate.address" .  | quote }}
            - name: RESOURCE_DIRECTORY_ADDRESS
              value: {{ include "plgd-cloud.resourcedirectory.address" .  | quote }}
            {{- if .Values.global.security.certManager.enable }}
            - name: LISTEN_TYPE
              value: "file"
            - name: LISTEN_FILE_CA_POOL
              value: "{{ .Values.global.security.certManager.tls.ca.mounthPath }}/{{ .Values.global.security.certManager.tls.ca.cert }}"
            - name: LISTEN_FILE_CERT_NAME
              value: {{ .Values.global.security.certManager.tls.listen.cert | quote }}
            - name: LISTEN_FILE_CERT_KEY_NAME
              value: {{ .Values.global.security.certManager.tls.listen.key | quote }}
            - name: LISTEN_FILE_CERT_DIR_PATH
              value: {{ .Values.global.security.certManager.tls.listen.mounthPath | quote }}
            - name: LISTEN_FILE_DISABLE_VERIFY_CLIENT_CERTIFICATE
              value: {{ .Values.coapgateway.tls.listen.disableVerifyClientCrt | quote }}
            - name: DIAL_TYPE
              value: "file"
            - name: DIAL_FILE_CA_POOL
              value: "{{ .Values.global.security.certManager.tls.ca.mounthPath }}/{{ .Values.global.security.certManager.tls.ca.cert }}"
            - name: DIAL_FILE_CERT_NAME
              value: {{ .Values.global.security.certManager.tls.dial.cert | quote }}
            - name: DIAL_FILE_CERT_KEY_NAME
              value: {{ .Values.global.security.certManager.tls.dial.key | quote }}
            - name: DIAL_FILE_CERT_DIR_PATH
              value: {{ .Values.global.security.certManager.tls.dial.mounthPath | quote }}
            {{- end }}
            {{- if .Values.coapgateway.debugGrpc }}
            - name: GODEBUG
              value: {{ .Values.setup.grpc.godebug | quote}}
            - name: GRPC_TRACE
              value: {{ .Values.setup.grpc.trace | quote}}
            - name: GRPC_VERBOSITY
              value: {{ .Values.setup.grpc.verbosity | quote}}
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: {{ .Values.setup.grpc.verbosityLevel | quote}}
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: {{ .Values.setup.grpc.severityLevel | quote}}
            {{- end }}
          volumeMounts:
          {{- if .Values.global.security.certManager.enable}}
            - name: ca-authority-crt
              mountPath: {{ .Values.global.security.certManager.tls.ca.mounthPath }}
            - name: dial-crt
              mountPath: {{ .Values.global.security.certManager.tls.dial.mounthPath }}
              readOnly: true
            - name: listen-crt
              mountPath: {{ .Values.global.security.certManager.tls.listen.mounthPath }}
              readOnly: true
          {{- end }}
          {{- with .Values.resources.coapgateway }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.global.security.certManager.enable}}
        - name: dial-crt
          secret:
            secretName: {{ include "plgd-cloud.dialCrtName" . }}
        - name: listen-crt
          secret:
            secretName: {{ include "plgd-cloud.coapgateway.listenCrtName" . }}
        - name: ca-authority-crt
          secret:
            secretName: {{ .Values.global.security.certManager.tls.ca.secret.name }}
      {{- end }}
      {{- with .Values.nodeSelector.coapgateway }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity.coapgateway }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations.coapgateway }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}